name: API Testing
on: [push]
jobs:
  Lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run lint
  Api-Tests:
    needs: Lint
    name: Run api-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install -g newman
      - run: newman run ./api_testing/Todoist-API.postman_collection.json -e ./api_testing/Todoist.postman_environment.json